### ISSUE TITLE
Kindly upload the lastfm and AToy data sets as well.

### ISSUE THREAD

**Issue by SyedTauhidUllahShah** [familyld/DeepCF#4]

**Comment by familyld** [comment]
Hi, @tauhidshah . First, thank you for your attention to our paper. The two data sets are uploaded now, feel free to use them in your experiments.  By the way, I would like to add that using other data sets is highly encouraged because this may help researchers explore the shortcomings of the existing research results.

**Comment by SyedTauhidUllahShah** [comment]
> Hi, @tauhidshah . First, thank you for your attention to our paper. The two data sets are uploaded now, feel free to use them in your experiments. By the way, I would like to add that using other data sets is highly encouraged because this may help researchers explore the shortcomings of the existing research results.

@familyld Thank you for your kind response. I will highly appreciate it.
