### ISSUE TITLE
How to use the code on other data sets?

### ISSUE THREAD

**Issue by SyedTauhidUllahShah** [familyld/DeepCF#5]
Hello there,
I tried to run the code with the AMusic dataset. The results of the CFNet are not correct with the current settings.

**Comment by familyld** [comment]
To address the problem, you need to provide more details about your training setting and results.

**Comment by SyedTauhidUllahShah** [comment]
> To address the problem, you need to provide more details about your training setting and results.

I used the same settings(lr=0.0001,epochs=20 and sgd). The results are HR=0.1582 and NDCG=0.0699. I tried to delete the already given pre-train models for ml-1m. Then I execute the CFNet and after 20  epochs(with sgd and lr= 0.0001) I got HR=0.5341 and NDCG=0.3018. I just wanna know that how did you train it for the existing Pre-Train files? I would really appreciate if you can provide the hyperparameter values.

**Comment by familyld** [comment]
First, you need to run the following commands to obtain pre-trained models for AMusic:

Run CFNet-rl:
`python DMF.py --dataset AMusic --epochs 20`

Run CFNet-ml:
`python MLP.py --dataset AMusic --epochs 20`

Then you can use the pre-trained models to run CFNet, which should yield a comparable result as presented in our paper:

`python CFNet.py --dataset ml-1m --epochs 20 --lr 0.0001  --learner sgd  --dmf_pretrain PathToYourPretrainedDMFFile --mlp_pretrain PathToYourPretrainedMLPFile`

Notice, since AMusic has more items than users, you should use more dimensions for userlayer ([1024, 64]) and fewer dimensions for itemlayer ([512, 64]). You can change it in DMF.py.

**Comment by familyld** [comment]
I change the original heading “AMusic results are not accurate.” to “How to use the code on other data sets?” to better fit this issue.
